### ISSUE TITLE
Question for why using vision data to train audio

### ISSUE THREAD

**Issue by lntzm** [DAMO-NLP-SG/Video-LLaMA#103]
您好，您在这个issue里解释了Video-LLaMA使用了vision-text通过imagebind来间接训练audio的适配器：
https://github.com/DAMO-NLP-SG/Video-LLaMA/issues/56#issuecomment-1657382944
想请问一下这么做的好处是什么，为什么不直接使用audio来训练而是通过这种间接的方式呢？

**Comment by hangzhang-nlp** [comment]
因为audio-text对齐的数据比较稀缺。
