### ISSUE TITLE
Discrepancy in Pre-trained Weights and Performance Degradation

### ISSUE THREAD

**Issue by leng-yue** [DAMO-NLP-SG/Video-LLaMA#110]
Thanks for the amazing work you've put in! While the readme states that only certain layers (Q-Former, PE, and linear projection) are trainable during cross-modal training, I found that the sha256 checksums of the video-llama's `
DAMO-NLP-SG/Video-LLaMA-2-13B-Finetuned/llama-2-13b-chat-hf/pytorch_model-00001-of-00003.bin` and the official `meta-llama/Llama-2-13b-chat-hf/pytorch_model-00001-of-00003.bin` differ. This difference appears to lead to a drop in performance when using the official weights. Can you provide other details?

**Comment by lixin4ever** [comment]
We haven't noticed this before. May I know which one leads to poor performance? The meta-llama one or the one we provide?

**Comment by leng-yue** [comment]
There is a performance drop if I use meta-llm's weight replace the provided one. However, I didn't see a performance drop when pretraining and fintuning from scratch using freezed meta-llm.

**Comment by lixin4ever** [comment]
Its very likely that the released q-former weights are only compatible with the llama2 weights we provided and that's also the reason why you didn't encounter the same issue when pretraining and finetuning from scratch with the official llama2. 

Thanks for pointing out this, we will verify the difference later.
