### ISSUE TITLE
IndentationError in train_configs/video_llama_stage2_finetune.yaml

### ISSUE THREAD

**Issue by rese1f** [DAMO-NLP-SG/Video-LLaMA#12]
Thanks for your great work. Please fix the IndentationError in train_configs/video_llama_stage2_finetune.yaml, lol.

**Comment by rese1f** [comment]
also the param "tokenizer_name" for each dataset in config is missing, you give
`if self.config.tokenizer_name:
    tokenizer_name = self.config.tokenizer_name 
else:
    tokenizer_name = '/mnt/workspace/ckpt/vicuna-13b/'`
 in video_llama/datasets/builders/instruct_builder.py line 35 but forget to add them to config

**Comment by hangzhang-nlp** [comment]
Thanks, it is fixed now.
