### ISSUE TITLE
能否更新下README

### ISSUE THREAD

**Issue by Junphy-Jan** [DAMO-NLP-SG/Video-LLaMA#122]
感谢开源工作！

另外既然 llama2的版本不需要delta weights and separate Q-former weights了，能否更新下README 把安装使用过程更新下？

**Comment by lixin4ever** [comment]
感谢提醒，README已更新，旧版Video-LLaMA的README也可以在[这里](https://github.com/DAMO-NLP-SG/Video-LLaMA/blob/main/README_Vicuna.md)查看.
