### ISSUE TITLE
Interesting prompt template

### ISSUE THREAD

**Issue by tian1327** [DAMO-NLP-SG/Video-LLaMA#126]
Thanks for the great work! I am wondering if you could shed some light on the prompt template used in the model. I find it particularly interesting to prompt by "eyes" and "ears" etc. to guide the model to focus on different features. How did you find such prompts? Did u see it used in other works?

"Close your eyes, open your ears and you imagine only based on the sound that: <ImageHere>. \
                Close your ears, open your eyes and you see that <Video><ImageHere></Video>.  \
                Now answer my question based on what you have just seen and heard."

**Comment by hangzhang-nlp** [comment]
Thank you for your kind words and for your intriguing question! The prompt template you mentioned, involving "eyes" and "ears," is quite interesting and serves as a creative way to guide the LLM to distinguish different sensory features. Regarding the origin of this prompt template, it's actually an innovation developed by our team.
