### ISSUE TITLE
The question about llama parameters during pre-training and fine-tuning.

### ISSUE THREAD

**Issue by cooper12121** [DAMO-NLP-SG/Video-LLaMA#130]
"During pre-training and fine-tuning, are the parameters of the llama frozen?"

**Comment by lixin4ever** [comment]
Right, the parameters of LLMs are kept frozen during both pre-training and fine-tuning.

**Comment by cooper12121** [comment]
> Right, the parameters of LLMs are kept frozen during both pre-training and fine-tuning.

Translate: Thank you for your reply. Have you tested some multimodal tasks such as multimodal NER and relation extraction? How does only fine-tuning Q-former perform when llama parameters are frozen?
