### ISSUE TITLE
How to select the video encoder of  the chinese version with BiLLA or Ziya ?

### ISSUE THREAD

**Issue by cm-xcju** [DAMO-NLP-SG/Video-LLaMA#144]
The project said " Support video-grounded chat in Chinese with BiLLA and Ziya" and provided the parameters of the fintuned BiLLA and Ziya. However, where are the parmaters of  the imagebind encoder that should be used for Chinese LLMs?

**Comment by cm-xcju** [comment]
Where is the VL and AL parmeters for Chinese version

**Comment by lixin4ever** [comment]
Thank you for your attention. 

Only the very early version of our Video-LLaMA uses BiLLA and Ziya to enable Chinese chatting while the officially released version (i.e., Video-LLaMA with both the Vision-Language branch and the Audio-Language branch) does not support Chinese anymore. So, there is no VL or AL parameter for Chinese.
