### ISSUE TITLE
the image size is defined in .yaml files but they are also manually set here and there

### ISSUE THREAD

**Issue by amirsafaei** [DAMO-NLP-SG/Video-LLaMA#17]
Great work,
I noticed the image size is fixed to 224 * 224 in a few files despite being a parameter in .yaml files. Also, I wonder if any size video would work (if someone wants to use your code to fine-tune their own data) if we just change the image size parameter. (considering some of the pre-trained models maybe work better with that fixed image size?). I'll appreciate it if you could explain what's the best approach if I want to use your code to fine-tune on a different video size(not using your model weight but rather your code)

**Comment by hangzhang-nlp** [comment]
The original videos that we used for training are of any sizes, they will be resized to 224 * 224 during the reading process. See https://github.com/DAMO-NLP-SG/Video-LLaMA/blob/6ca4b1c171103a17c4219c64e7da9e3b7ac6ad30/video_llama/datasets/datasets/video_instruct_dataset.py#LL74C30-L74C40. 
224*224 is the size set in the Image Encoder(BLIP-2) we used.

**Comment by hangzhang-nlp** [comment]
```
from decord import VideoReader
vr = VideoReader(uri=video_path, height=height, width=width)   # 
```
