### ISSUE TITLE
When the "[06.08] 🚀🚀 Next BIG update is on the way!!" will be available? today is [06, 08]

### ISSUE THREAD

**Issue by tensorboy** [DAMO-NLP-SG/Video-LLaMA#19]
As the title

**Comment by lixin4ever** [comment]
The checkpoints for the audio-language branch have been uploaded. Due to the limit of GPU memory, the online interactive demo for the latest Video-LLaMA is not ready yet and the current running demo on Hugging Face is still for the previous version.
