### ISSUE TITLE
The link of the weights unavailable

### ISSUE THREAD

**Issue by tensorboy** [DAMO-NLP-SG/Video-LLaMA#2]
<img width="1003" alt="Screen Shot 2023-05-10 at 2 32 48 PM" src="https://github.com/DAMO-NLP-SG/Video-LLaMA/assets/17189055/096de694-2c8d-45d3-aa09-4aedd3ae653d">

**Comment by lixin4ever** [comment]
Thanks for your information. Just update the link and it should work now.
