### ISSUE TITLE
Explanation about "data" log parameter

### ISSUE THREAD

**Issue by SushantGautam** [DAMO-NLP-SG/Video-LLaMA#25]
![image](https://github.com/DAMO-NLP-SG/Video-LLaMA/assets/16721983/1927bed1-a4fb-44a0-803b-e85b9fc1ca83)
The values in the data are always zero. What does it represent?

**Comment by SushantGautam** [comment]
Ah! Looks like "the time taken for data loading or preprocessing for the current iteration".
Maybe we can change formatting to display some significant info rather than just zeros.

**Comment by SushantGautam** [comment]
![image](https://github.com/DAMO-NLP-SG/Video-LLaMA/assets/16721983/2ae51bb1-74b0-4512-94ac-409852675c8e)
I tried to train: videollama_stage1_pretrain with just cc_sbu_align dataset. But the loss doesn't settle well. It is oscillating around 2.5-3. Do you know if this is normal?

**Comment by hangzhang-nlp** [comment]
Yes, it is normal.
