### ISSUE TITLE
size mismatch error

### ISSUE THREAD

**Issue by feymanwang** [DAMO-NLP-SG/Video-LLaMA#28]
```shell
python demo_audiovideo.py --cfg-path eval_configs/video_llama_eval_withaudio.yaml  --gpu-id 3
``` 

<img width="1217" alt="企业微信截图_16866218696720" src="https://github.com/DAMO-NLP-SG/Video-LLaMA/assets/33916828/d855f2fb-c45d-45b3-b6b2-735a366e8f61">

**Comment by DeerEyre** [comment]
this is my yaml.  and it can run
model:
  arch: video_llama
  model_type: pretrain_vicuna
  freeze_vit: True
  freeze_qformer: True
  max_txt_len: 512
  end_sym: "###"
  low_resource: False

  frozen_llama_proj: False

  llama_model: "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-search/gongshuai06/mt_bert_docker_row/Big_model/Model_Zoo/vicuna-7b/" 
  imagebind_ckpt_path: "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-search/gongshuai06/mt_bert_docker_row/Big_model/Video_model/Video_LLaMa/imagebind/"

  fusion_head_layers: 2
  max_frame_pos: 32
  fusion_header_type: "seqTransf"

  ckpt: "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-search/gongshuai06/mt_bert_docker_row/Big_model/Video_model/Video_LLaMa/pretrained_finetuned_weights/finetune-vicuna7b-v2.pth"
  ckpt_2: "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-search/gongshuai06/mt_bert_docker_row/Big_model/Video_model/Video_LLaMa/audio/finetune_vicuna7b_audiobranch.pth"


datasets:
  webvid:
    vis_processor:
      train:
        name: "alpro_video_eval"
        n_frms: 8
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"

run:
  task: video_text_pretrain

**Comment by DeerEyre** [comment]
i am a newfish about this project. if u want to study together, you can take this weixinID: SweetDearieGniT or qq 837074044

**Comment by DeerEyre** [comment]
i am a newfish about this project. if u want to study together, you can take this weixinID: SweetyDearieGniT or qq 837074044

**Comment by feymanwang** [comment]
> this is my yaml. and it can run model: arch: video_llama model_type: pretrain_vicuna freeze_vit: True freeze_qformer: True max_txt_len: 512 end_sym: "###" low_resource: False
> 
> frozen_llama_proj: False
> 
> llama_model: "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-search/gongshuai06/mt_bert_docker_row/Big_model/Model_Zoo/vicuna-7b/" imagebind_ckpt_path: "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-search/gongshuai06/mt_bert_docker_row/Big_model/Video_model/Video_LLaMa/imagebind/"
> 
> fusion_head_layers: 2 max_frame_pos: 32 fusion_header_type: "seqTransf"
> 
> ckpt: "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-search/gongshuai06/mt_bert_docker_row/Big_model/Video_model/Video_LLaMa/pretrained_finetuned_weights/finetune-vicuna7b-v2.pth" ckpt_2: "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-search/gongshuai06/mt_bert_docker_row/Big_model/Video_model/Video_LLaMa/audio/finetune_vicuna7b_audiobranch.pth"
> 
> datasets: webvid: vis_processor: train: name: "alpro_video_eval" n_frms: 8 image_size: 224 text_processor: train: name: "blip_caption"
> 
> run: task: video_text_pretrain

vicuna7b works well  for me

**Comment by feymanwang** [comment]
I found the error comes from the usage of vicuna-13b model。
But when I use vicuna-7b model, everything works well.
<img width="731" alt="企业微信截图_16866408235172" src="https://github.com/DAMO-NLP-SG/Video-LLaMA/assets/33916828/0378edcd-5915-4b2b-b2f8-67b865f2f161">

**Comment by DeerEyre** [comment]
同学您好，你有什么联系方式可以添加吗，想和你交流一下学习心得

**Comment by DeerEyre** [comment]
同学您好，你有什么联系方式可以添加吗，想和你交流一下学习心得，我碰到了一个阻碍性问题想和你讨论一下，我的微信是SweetyDearieGniT 或者 qq 837074044

**Comment by feymanwang** [comment]
> @SushantGautam We use **vicuna-{7b/13b}-delta-v0** instead of the latest ones (i.e., vicuna-{7b/13b}-delta-v1.1) as the language decoder of Video-LLaMA. To transform the v0 delta weights to the full weights of vicuna, we directly use an old version of apply_delta.py provided by FastChat and this script may not be compatible with v1.1 delta weights.

I tried the vicuna-13b-delta-v0, the error came again and same.

In vicuna-13b-delta-v0 config file, the hidden size is 5120,  but the size in finetune-vicuna7b-v2 , used in Audio-Language Branch , is 4096, it's the vicuna-7b hidden size. 

so I think te error comes from the different size model between  Audio-Language Branch (vicuna-7b) and Vision-Language Branch(13b).   

If I am right, where can I get the vicuna-13b model in Audio-Language Branch?

**Comment by SushantGautam** [comment]
> > @SushantGautam We use **vicuna-{7b/13b}-delta-v0** instead of the latest ones (i.e., vicuna-{7b/13b}-delta-v1.1) as the language decoder of Video-LLaMA. To transform the v0 delta weights to the full weights of vicuna, we directly use an old version of apply_delta.py provided by FastChat and this script may not be compatible with v1.1 delta weights.
> 
> I tried the vicuna-13b-delta-v0, the error came again and same.
> 
> In vicuna-13b-delta-v0 config file, the hidden size is 5120, but the size in finetune-vicuna7b-v2 , used in Audio-Language Branch , is 4096, it's the vicuna-7b hidden size.
> 
> so I think te error comes from the different size model between Audio-Language Branch (vicuna-7b) and Vision-Language Branch(13b).
> 
> If I am right, where can I get the vicuna-13b model in Audio-Language Branch?

I think the audio support is ONLY for Vicuna-7B by now. Check README

**Comment by lixin4ever** [comment]
@feymanwang I am afraid that you have to use vicuna-7b because the latest version of Video-LLaMA only supports vicuna-7b as the language decoder.
