### ISSUE TITLE
transformers version issue

### ISSUE THREAD

**Issue by yzxyzh** [DAMO-NLP-SG/Video-LLaMA#29]
I notice that in your work, the required transformers version is 4.28.0, which, if I'm not mistaking, had a bug with llama tokenizer. Have you tested higher versions of transformers? If I'm using, for example, version 4.29, will this affect the model converted?

**Comment by lixin4ever** [comment]
Not tested this before. I suggest you try our Video-LLaMA with transformers==4.28.0 first and then upgrade transformers to 4.29.x to compare the difference between the model outputs. If there exists any unexpected result, feel free to create a PR.
