### ISSUE TITLE
[VideoChat] Video instruction data

### ISSUE THREAD

**Issue by Andy1621** [DAMO-NLP-SG/Video-LLaMA#3]
Hi! It's interesting to build a chatbot for video understanding!
In our project "[VideoChat🦜](https://github.com/OpenGVLab/Ask-Anything/tree/main/video_chat): Chat-Centric Video Understanding", we also build an interesting chatbot🤖 for **both image and video**. More importantly, we have released **11K video instruction data for spatiotemporal reasoning**. You can also utilize them to **enhance your project** 💪🏻!
**If you have tried it, don't forget to give me the feedback. We will improve the data in the future.**
Project: https://github.com/OpenGVLab/Ask-Anything/tree/main/video_chat
Paper: [https://arxiv.org/abs/2305.06355](https://t.co/mWFmw6wr9b)

![image](https://pbs.twimg.com/media/Fv1BHVBaEAE4bOn?format=jpg&name=large)

**Comment by hangzhang-nlp** [comment]
Awesome!!!

**Comment by rese1f** [comment]
Awesome!
