### ISSUE TITLE
The effect gap is too large

### ISSUE THREAD

**Issue by DeerEyre** [DAMO-NLP-SG/Video-LLaMA#30]
I tuned the demo file and ran it, but I got terrible results, not as good as in the hugging-face demo, and also repeating the question asked at the end of each answer. I don't know what caused it.

The following is my configuration file, is there any problem?

****
model:
  arch: video_llama
  model_type: pretrain_vicuna
  freeze_vit: True
  freeze_qformer: True
  max_txt_len: 512
  end_sym: "###"
  low_resource: False

  frozen_llama_proj: False

  llama_model: "vicuna-7b/" 
  imagebind_ckpt_path: "imagebind/"

  fusion_head_layers: 2
  max_frame_pos: 32
  fusion_header_type: "seqTransf"

  ckpt: "finetune-vicuna7b-v2.pth"
  ckpt_2: "finetune_vicuna7b_audiobranch.pth"

datasets:
  webvid:
    vis_processor:
      train:
        name: "alpro_video_eval"
        n_frms: 8
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"

run:
  task: video_text_pretrain

**Comment by lixin4ever** [comment]
Please make sure you are using vicuna-7B-delta-v0 instead of vicuna-7B-delta-v1.1.
