### ISSUE TITLE
how to get the cc3m filter_cap.json data

### ISSUE THREAD

**Issue by PeterMao11** [DAMO-NLP-SG/Video-LLaMA#32]
I have download LLaVA-CC3M-Pretrain-595K but don't found the filter_cap.json,how can i get the filter_cap.json

**Comment by SushantGautam** [comment]
![image](https://github.com/DAMO-NLP-SG/Video-LLaMA/assets/16721983/2c116766-1a16-4d03-9984-b2667ccb2fb0)
You can transform the CSV/ or the annotation format you have to this format.

**Comment by MengHao666** [comment]
> SushantGautam

how could I transform the original data info to the one you mentioned?

**Comment by SushantGautam** [comment]
> > SushantGautam
> 
> how could I transformer the original data info to the one you mentioned?
write a python script
