### ISSUE TITLE
Quantize Video-LLama with SqueezeLLM

### ISSUE THREAD

**Issue by vegax87** [DAMO-NLP-SG/Video-LLaMA#35]
Since Video-LLama still use fp16, I think it's better to integrate a lossless quantization such as SqueezeLLM that already supports Vicuna 7B and 13B

source: https://github.com/SqueezeAILab/SqueezeLLM

**Comment by lixin4ever** [comment]
Thank you for your suggestions. Actually, our running demo usually becomes unusable due to the issue of "CUDA Out of memory" even with vicuna-7B. We will definitely consider this feature in the near future.
