### ISSUE TITLE
虽然git里发布了13b的llama模型，但audio模型还是7b的，这样启动demo程序，会报错，维度不兼容，咋整？

### ISSUE THREAD

**Issue by willzli** [DAMO-NLP-SG/Video-LLaMA#38]

**Comment by willzli** [comment]
13b模型发布的时候，还没有audio这一路。

**Comment by lixin4ever** [comment]
抱歉让你产生了一些困惑

我之前在另一个issue里回复过，VL/AL的checkpoint是跟language decoder绑定的，同时如果想要正常跑起来VL和AL分支是共享language decoder的，所以这就决定了无法同时加载video 13b的参数和audio 7b的参数
