### ISSUE TITLE
Can this project be directly applied in chinese scenarios?

### ISSUE THREAD

**Issue by jetwu-create** [DAMO-NLP-SG/Video-LLaMA#4]

**Comment by lixin4ever** [comment]
@jetwu-create Sorry for the late reply! Our Video-LLaMA is now capable to handle Chinese queries and generate some reasonable responses! The two new Chinese variants [Video-LLaMA-BiLLA](https://huggingface.co/DAMO-NLP-SG/Video-LLaMA-Series/resolve/main/finetune-billa7b-zh.pth) and [Video-LLaMA-Ziya](https://huggingface.co/DAMO-NLP-SG/Video-LLaMA-Series/resolve/main/finetune-ziya13b-zh.pth)) are respectively built on top of [BiLLa-7B](https://huggingface.co/Neutralzz/BiLLa-7B-SFT) and [Ziya-13B](https://huggingface.co/IDEA-CCNL/Ziya-LLaMA-13B-v1) and already uploaded to huggingface, hope they will make your work easier.

**Comment by jetwu-create** [comment]
Thanks!
