### ISSUE TITLE
key error['API-TOKEN']

### ISSUE THREAD

**Issue by justinwking** [DAMO-NLP-SG/Video-LLaMA#40]
I just installed, "Video LLaMa finetune vicuna7B". When running the app.py I get key error['API-TOKEN'] when I get to the loading QFormer stage. I can see that the video-llama.py is looking for os.environ['API_TOKEN'] but where do I need to go in order to get an api token? is this a hugging face token? Or possibly a LLaMa token? What is the best way to save the token, so that os.environ['API_TOKEN'] can find it? Thank you!

**Comment by justinwking** [comment]
I realized there are a set of instructions that I have missed, so I will close this case and open another case if I have issues after following the additional instructions.

**Comment by Mikes95** [comment]
How did you manage to solve it?

**Comment by justinwking** [comment]
I apologize that I forgot what I did specifically, but if you remind me of the link of instructions you are using it might help jog my memory.

**Comment by Mikes95** [comment]
I'm generally trying to run a code demo of Video-Llama on my machine. I started with the Hugging Face repository, but I don't think that's the right approach.
