### ISSUE TITLE
Which conference do you submit this paper?

### ISSUE THREAD

**Issue by jacob-kang** [DAMO-NLP-SG/Video-LLaMA#42]
Hi.
Thanks for your great works.

I'm a new researcher. And I'm interested in Video understanding field.

I read your paper. And I wonder what conference did you submit?
The form looks like NIPS.

Thanks.
kind regards.

**Comment by lixin4ever** [comment]
Thank you for your attention.

We just adopted the laTeX template from NeurIPS (with some modifications) and we haven't submitted the technical report of our Video-LLaMA to any conference/journal by now.
