### ISSUE TITLE
why keep "###" before instruct text?

### ISSUE THREAD

**Issue by Cescfangs** [DAMO-NLP-SG/Video-LLaMA#44]
https://github.com/DAMO-NLP-SG/Video-LLaMA/blob/1728e14f12cbe10287a11395b486ac522ea64083/video_llama/datasets/datasets/video_instruct_dataset.py#L250-L252

I was reading `_mask_targets()`, I guess this function is using mask to ignore loss from instruct text, but why do you manually keep [curr_idx: curr_idx+2] which is "###" before the actual instruct text?

**Comment by hangzhang-nlp** [comment]
The assistant will learn to generate "###" if it wants to end the current round. So "###"  can be understood as the EOS flag of each session.

**Comment by Cescfangs** [comment]
> The assistant will learn to generate "###" if it wants to end the current round. So "###" can be understood as the EOS flag of each session.

Thanks for the reply, I understand "###" works like EOS here, and I think the "###" in assistant text is more like EOS? howerver why do we want assistant to learn EOS before instruct?

**Comment by hangzhang-nlp** [comment]
During inference, we will stop generating tokens once the assistant outputs "###".  
Suppose that the training data is " ###Human: Hi. ###Assistant: Hi, can I help you. ###Human: yes".
The content which needs to calculate loss is "Hi, can I help you. ###". So the model can learn to generate "###" as the end flag of his reply.

**Comment by Cescfangs** [comment]
> During inference, we will stop generating tokens once the assistant outputs "###". Suppose that the training data is " ###Human: Hi. ###Assistant: Hi, can I help you. ###Human: yes". The content which needs to calculate loss is "Hi, can I help you. ###". So the model can learn to generate "###" as the end flag of his reply.

I mean you are also keep the  first "###"(the one before "Human: Hi...").

**Comment by hangzhang-nlp** [comment]
Oh, I see. This place is just for convenience, and you can add a judgment, mask the first "###".

**Comment by Cescfangs** [comment]
Okay, thanks for the confirmation
