### ISSUE TITLE
Can I Instruction Fine-tuning the model with my dataset using 4*3090?

### ISSUE THREAD

**Issue by aixiaodewugege** [DAMO-NLP-SG/Video-LLaMA#45]
Hi, thanks for your brilliant work. I want to finetune the model on my dataset. Can it be done with 4 * 3090? Or how much GPU memory is necessary?

**Comment by lixin4ever** [comment]
We use 8*A100-80G during both pre-training and fine-tuning. We haven't yet tested on other GPUs with less memory but I think decreasing batch size per gpu while keeping the global batch size identical should work

**Comment by aixiaodewugege** [comment]
Thanks for your reply! 

How much GPU memory is needed at the inference stage? I noticed you are using A100. Can I use one 3090? And can I use multi GPUS to inference?

**Comment by lixin4ever** [comment]
Given Vicuna-7B as language decoder, >24GB for VL-only Video-LLaMA (i.e., the previous version of LLaMA) and >40GB for the current version of LLaMA. These numbers are just based on our observation and may not be very accurate.

**Comment by QYY1028** [comment]
> Hi, thanks for your brilliant work. I want to finetune the model on my dataset. Can it be done with 4 * 3090? Or how much GPU memory is necessary?

Hi, have you successfully finetuned the model with 4*3090?
