### ISSUE TITLE
Is is possible to insturct-finetune Video-LLaMA in 8 * 24 GB Nvidia A5000

### ISSUE THREAD

**Issue by Fr0zenCrane** [DAMO-NLP-SG/Video-LLaMA#46]
Thanks for sharing the code and this brilliant work! I wonder if i can run insturct-finetune Video-LLaMA in 8 * 24 GB Nvidia A5000 using my own video datasets?

**Comment by aixiaodewugege** [comment]
Hi, looks we are facing the same problem. 

Would you mind if we exchange contact information and communicate via WeChat? I believe it would be a great opportunity for us to connect further.

**Comment by lixin4ever** [comment]
We haven't yet tested on other GPUs with GPU memory less than 80G but I think decreasing batch size per gpu while keeping the global batch size identical should work
