### ISSUE TITLE
搭建demo返回错误的结果

### ISSUE THREAD

**Issue by PeterMao11** [DAMO-NLP-SG/Video-LLaMA#48]
模型加载没有问题，模型参数如下
model:
  arch: video_llama
  model_type: pretrain_vicuna
  freeze_vit: True
  freeze_qformer: True
  max_txt_len: 512
  end_sym: "###"
  low_resource: False

  frozen_llama_proj: False

  llama_model: "vicuna-7b-delta-v0"
  imagebind_ckpt_path: "imagebind_huge.pth"

  fusion_head_layers: 2
  max_frame_pos: 32
  fusion_header_type: "seqTransf"

  ckpt: "finetune-vicuna7b-v2.pth"
  ckpt_2: "finetune_vicuna7b_audiobranch.pth"

datasets:
  webvid:
    vis_processor:
      train:
        name: "alpro_video_eval"
        n_frms: 8
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"

run:
  task: video_text_pretrain

**Comment by PeterMao11** [comment]
model:
  arch: video_llama
  model_type: pretrain_vicuna
  freeze_vit: True
  freeze_qformer: True
  max_txt_len: 512
  end_sym: "###"
  low_resource: False

  frozen_llama_proj: False

  llama_model: "vicuna-7b-delta-v0"
  imagebind_ckpt_path: "imagebind_huge.pth"

  fusion_head_layers: 2
  max_frame_pos: 32
  fusion_header_type: "seqTransf"

  ckpt: "finetune-vicuna7b-v2.pth"
  ckpt_2: "finetune_vicuna7b_audiobranch.pth"


datasets:
  webvid:
    vis_processor:
      train:
        name: "alpro_video_eval"
        n_frms: 8
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"

run:
  task: video_text_pretrain

**Comment by PeterMao11** [comment]
返回demo结果
![image](https://github.com/DAMO-NLP-SG/Video-LLaMA/assets/26111139/d739bad9-6c9a-4a37-b588-c72545112c60)

**Comment by PeterMao11** [comment]
在https://huggingface.co/openlm-research/open_llama_7b下载original LLaMA 模型，python apply_delta.py \
    --base llama_7b \
    --target vicuna-7b \
    --delta vicuna-7b-delta-v0进行转换

但返回结果如下

<img width="1320" alt="image" src="https://github.com/DAMO-NLP-SG/Video-LLaMA/assets/26111139/21af72f8-7cc9-420d-b8ba-2f9d55ac660f">

**Comment by lixin4ever** [comment]
你这个是open_llama, 不是llama, llama权重需要去官方仓库填写表格申请下载

**Comment by PeterMao11** [comment]
使用Video-LLaMA-BiLLA中文模型，除了llm和chpt修改配置，例如qformer,clip这些模型需要修改配置么

**Comment by lixin4ever** [comment]
不需要的，所有实验里visual encoder (ViT & Q-former)都是用的同一套，但是有一个问题就是中文模型目前我们没有添加对audio输入的支持 (也就是没有AL分支)，如果你需要使用Video-LLaMA-BiLLA的话，只能尝试运行VL-only Video-LLaMA, 可以参考一下[demo_video.py](https://github.com/DAMO-NLP-SG/Video-LLaMA/blob/main/demo_video.py)和[video_llama_eval.yaml](https://github.com/DAMO-NLP-SG/Video-LLaMA/blob/main/eval_configs/video_llama_eval.yaml)
