### ISSUE TITLE
Inquiry about “max_epoch” values for pre-training and fine-tuning

### ISSUE THREAD

**Issue by YasmineXXX** [DAMO-NLP-SG/Video-LLaMA#50]
I would like to inquire about the `max_epoch` values set for pre-training and fine-tuning. Are they set to 5 and 3 as  in the config file, respectively? I tried running the fine-tuning code with these values, but the results were not as coherent as the fine-tuned models provided by the official repository. Therefore, I would like to confirm if these are the correct values.

Thank you for your help and for sharing your work with the community.

**Comment by lixin4ever** [comment]
Great to receive your feedback on fine-tuning Video-LLaMA. We find that we haven't updated the yaml files for fine-tuning the VL branch of Video-LLaMA, which could be a probable reason that causes the inconsistency.

Please refer to our latest commit https://github.com/DAMO-NLP-SG/Video-LLaMA/commit/ed86c27b881700a7422215a2d53396e7be47b10e for more details:

**Comment by YasmineXXX** [comment]
I found that you did not modify the value of 'max_epoch' in the updated 'video_llama_stage2_finetune.yaml' file. I would like to clarify whether max_epoch is set to 3 during the actual fine-tuning?

**Comment by lixin4ever** [comment]
Yes, it is 3.

**Comment by YasmineXXX** [comment]
Thank you, and thank you again for your selfless sharing.

**Comment by YasmineXXX** [comment]
Got it. Thank you again for your selfless sharing.
