### ISSUE TITLE
是否提供基于ziya的inference code？

### ISSUE THREAD

**Issue by liu6381810** [DAMO-NLP-SG/Video-LLaMA#51]
想load一个基于ziya的video-llama模型跑video caption任务，目前是否提供类似的inference脚本。或者直接从demo.py里去改吗？

**Comment by lixin4ever** [comment]
目前只有VL-only Video-LLaMA (也就是只有视觉分支的Video-LLaMA)支持中文, 可以尝试修改[demo_video.py](https://github.com/DAMO-NLP-SG/Video-LLaMA/blob/main/demo_video.py)和[video_llama_eval.yaml](https://github.com/DAMO-NLP-SG/Video-LLaMA/blob/main/eval_configs/video_llama_eval.yaml)来运行本地demo并进行推理

需要注意的是，我们只是在第二阶段训练中加入了11K翻译后的指令微调数据，可能训练得不是很充分
