### ISSUE TITLE
模型输出截断

### ISSUE THREAD

**Issue by xmy0916** [DAMO-NLP-SG/Video-LLaMA#52]
https://github.com/DAMO-NLP-SG/Video-LLaMA/blob/main/video_llama/processors/blip_processors.py#L49C1-L49C1
这个预处理很奇怪，把句号感叹号都去掉了 大小写也没了，然后还写了个max_word在里面把训练数据截断到50个的长度 查了好久模型输出截断最后发现是这里的问题。不太清楚这么设计的原因是什么

**Comment by hangzhang-nlp** [comment]
一些video/image-caption的默认操作，follow BLIP的setting。
