### ISSUE TITLE
the ability of sentiment analysis

### ISSUE THREAD

**Issue by liziming5353** [DAMO-NLP-SG/Video-LLaMA#55]
Have you ever tried to complete sentiment analysis or emotion recognition tasks in videos? How does the model perform?

**Comment by zeroQiaoba** [comment]
We have tested video-llama for video emotion recognition tasks on MER2023 Dataset. Meanwhile, we also provide an audio-video-text aligned training framework on emotion recognition. Details can be found in https://github.com/zeroQiaoba/AffectGPT.

**Comment by lixin4ever** [comment]
Not tested before but you can check @zeroQiaoba's paper for reference.
