### ISSUE TITLE
[Stage2finetune数据集]VideoChat instruction data使用疑问

### ISSUE THREAD

**Issue by Aopolin-Lv** [DAMO-NLP-SG/Video-LLaMA#59]
您好，请问如果我想单独使用```11K video-based instructions from VideoChat```进行stage2finetune，需要提前将Webvid10M全部下载吗？还是说可以使用Webvid2.5M？

**Comment by hangzhang-nlp** [comment]
11k video 是从webvid 10M中采样得到的。你不用提前下载所有的webvid，可以只下载那11k的视频。

**Comment by Aopolin-Lv** [comment]
谢谢回复！

**Comment by ChaofanTao** [comment]
请问是否什么方便的方式下载11k视频？比如现成的11k视频的下载脚本，或者11k视频的链接
