### ISSUE TITLE
I'm also training this... I haven't downloaded webvid2.5m yet and then I found that you have done everything I want to do, hahahaha

### ISSUE THREAD

**Issue by xmy0916** [DAMO-NLP-SG/Video-LLaMA#6]
I'm also training this... I haven't downloaded webvid2.5m yet and then I found that you have done everything I want to do, hahahaha

**Comment by lixin4ever** [comment]
Glad to receive your recognition:grin: We are actually still at the very beginning stage of this direction and there is a large room for improvement, let's keep moving:grin:
