### ISSUE TITLE
config相关问题

### ISSUE THREAD

**Issue by yypurpose** [DAMO-NLP-SG/Video-LLaMA#62]
感觉README写的有点乱，为啥有vicuna13b的vision-language分支却没有vicuna13b的Audio-Language分支？能否给一套config组合能复现论文，感谢！
试了下在video_llama_eval_withaudio.yaml中设置
```
  llama_model: vicuna-7b-v0
  imagebind_ckpt_path: imagebind_model
  ckpt: finetune-vicuna7b-v2.pth
  ckpt_2: finetune_vicuna7b_audiobranch.pth
```
发现模型输出是有问题的，请问是怎么回事?

**Comment by yypurpose** [comment]
debug了一下发现是
https://github.com/DAMO-NLP-SG/Video-LLaMA/blob/main/video_llama/conversation/conversation_video.py#L225
这行的conv.sep2是None导致每次只split了第一个单词。。

**Comment by lixin4ever** [comment]
> 

感谢建议，我们最近会基于llama2-chat更新一版模型，到时候也会完善一下文档
