### ISSUE TITLE
demo无法正常运行？

### ISSUE THREAD

**Issue by yingfei1016** [DAMO-NLP-SG/Video-LLaMA#64]
模型运行一切正常，vicuna采用的是v0，所有参数如下：

model:
  arch: video_llama
  model_type: pretrain_vicuna
  freeze_vit: True
  freeze_qformer: True
  max_txt_len: 512
  end_sym: "###"
  low_resource: False

  frozen_llama_proj: False

  llama_model: "/data/huggingface/hub/vicuna-7b/" 
  imagebind_ckpt_path: "/data/huggingface/hub/imagebind/"

  fusion_head_layers: 2
  max_frame_pos: 32
  fusion_header_type: "seqTransf"

  ckpt: "/data/huggingface/hub/video_llama/finetune-vicuna7b-v2.pth" 
  ckpt_2: "/data/huggingface/hub/video_llama/finetune_vicuna7b_audiobranch.pth" 

datasets:
  webvid:
    vis_processor:
      train:
        name: "alpro_video_eval"
        n_frms: 8
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"

run:
  task: video_text_pretrain

但是运行demo后，无论输入什么视频和问题，返回的都只有一个单词：

![image](https://github.com/DAMO-NLP-SG/Video-LLaMA/assets/106943722/3cf150fe-e9d0-460a-b6bf-ceaecc04dc72)

**Comment by wanghao-cst** [comment]
I have the same issue. It is quite weird.

**Comment by yingfei1016** [comment]
我感觉是代码更新太频繁，导致有些更新错了。我回退到6月份的版本，结果就正常了。

**Comment by hangzhang-nlp** [comment]
更新导致的bug，已经修复，感谢反馈。
