### ISSUE TITLE
Errors using LLaMA2 weights

### ISSUE THREAD

**Issue by amy011872** [DAMO-NLP-SG/Video-LLaMA#68]
Thanks a lot for the great works!!
I am trying the demo_video.py and demo_audiovideo.py with LLAMA2 weights. I've downloaded llama-2-7b and llama-2-7b-chat, and  I've also cloned the Video-LLaMA-2-7B-Finetuned and Video-LLaMA-2-7B-Pretrained repos on HF.
I've modified ```eval_configs/video_llama_eval_only_vl.yaml``` and ```eval_configs/video_llama_eval_withaudio.yaml``` as following:
```
model_type: pretrain_vicuna
low_resource: True
llama_model: "Video-LLaMA-2-7B-Finetuned/llama-2-7b-chat-hf/"
 ckpt: "Video-LLaMA-2-7B-Pretrained/VL_LLaMA_2_7B_Pretrained.pth"  
 equip_audio_branch: False
```
Then I run ```python demo_video.py --cfg-path eval_configs/video_llama_eval_only_vl.yaml --model_type llama_v2``` and ```python demo_audiovideo.py  --cfg-path eval_configs video_llama_eval_withaudio.yaml  --model_type llama_v2```. Both return a syntax error such as 
```
File "demo_audiovideo.py", line 228
    [f"examples/dog.jpg", "Which breed is this dog? "],
                       ^
SyntaxError: invalid syntax
```

Please help me find out what's missing? 

In addition, I am also confused by what "set the llama_model, imagebind_ckpt_path, ckpt and ckpt_2" means, should I also download imagebind, miniGPT4, or any other things? (But "NO delta weights and separate Q-former weights anymore"?)
Thanks in advance!!!!!

**Comment by hangzhang-nlp** [comment]
1. I did not encounter "SyntaxError: invalid syntax", It could be a problem with your text editor or Python interpreter
2. These checkpoints are in the folder `Video-LLaMA-2-7B-Finetuned/` which you have downloaded from Huggingface Repo,
     llama_model ->'Video-LLaMA-2-7B-Finetuned/llama-2-7b-chat-hf/',
     imagebind_ckpt_path -> `Video-LLaMA-2-7B-Finetuned/imagebind_huge.pth`
     ckpt -> `Video-LLaMA-2-7B-Finetuned/VL_LLaMA_2_7B_Finetuned.pth`
     ckpt_2 -> `Video-LLaMA-2-7B-Finetuned/AL_LLaMA_2_7B_Finetuned.pth`

**Comment by amy011872** [comment]
Thank you for your advice, I successfully fix this error and set up as you suggest. 
However, I encounter another error with regard this line ```lama_model ->'Video-LLaMA-2-7B-Finetuned/llama-2-7b-chat-hf/',```:
 ```
HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'Video-LLaMA-2-7B-Finetuned/llama-2-7b-chat-hf/'. Use `repo_type` 
argument if needed.
```
I tried ```DAMO-NLP-SG/Video-LLaMA-2-7B-Finetuned```, ```Video-LLaMA-2-7B-Finetuned```, and full directory to the   Video-LLaMA-2-7B-Finetuned file, but none of them work. Please help me figure out, thank you so much!!!
