### ISSUE TITLE
HFValidationError using Video-LLaMA-2-7B-Finetuned

### ISSUE THREAD

**Issue by amy011872** [DAMO-NLP-SG/Video-LLaMA#76]
Thank you for the quick response in my previous issue #68 !
However, as I move on and set up as you suggest, I encounter another error with regard this line ```lama_model ->'Video-LLaMA-2-7B-Finetuned/llama-2-7b-chat-hf/',```:
```
HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'Video-LLaMA-2-7B-Finetuned/llama-2-7b-chat-hf/'. Use `repo_type` argument if needed.
```
I tried replacing it with ```lama_model ->'DAMO-NLP-SG/Video-LLaMA-2-7B-Finetuned'```, ```Video-LLaMA-2-7B-Finetuned```, and the full directory to the Video-LLaMA-2-7B-Finetuned local file, but none of them work. Could you please help me figure it out, thank you so much!!!

I also have some follow-up questions regarding the demo file in Video-LLaMA.

1. If I successfully make the demo_video.py or demo_audiovideo.py work, would it be the same as [HF Space](https://huggingface.co/spaces/DAMO-NLP-SG/Video-LLaMA)? Given that in this HF space, the model constantly hallucinates or replies sth like this "________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________\" whenever it encounters difficult questions (I guess). Is this a normal response that would also happen even if I use llama-v2 in my local machine?
2. Is there another way to use llama-v2-version of Video-LLaMA locally, where I require no frontend interface like Gradio, but only intends to use for loop to test a few data? 

Thank you again for your time and effort!!

**Comment by hangzhang-nlp** [comment]
1. llama_model ->`Video-LLaMA-2-7B-Finetuned/llama-2-7b-chat-hf/`,  not `Video-LLaMA-2-7B-Finetuned/`
2. Hallucinates are normal when the video or query is difficult.
3. Of course you can write other test code, some functions are helpful in 'demo_audiovideo.py`

**Comment by amy011872** [comment]
Thank you! But I did try ```llama_model ->Video-LLaMA-2-7B-Finetuned/llama-2-7b-chat-hf/``` from the very beginning and it raises the error I mentioned
```
HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'Video-LLaMA-2-7B-Finetuned/llama-2-7b-chat-hf/'. Use `repo_type` 
argument if needed.
```

**Comment by hangzhang-nlp** [comment]
'your_path/Video-LLaMA-2-7B-Finetuned/llama-2-7b-chat-hf/`
