### ISSUE TITLE
About commercial use of weights and code in case of llama2

### ISSUE THREAD

**Issue by codgas** [DAMO-NLP-SG/Video-LLaMA#79]
Hello,

I've noticed some discrepancies regarding the licensing terms when using LLAMA2 as a text decoder:

- On both the GitHub repository and Hugging Face, the license is stated as `BSD 3-Clause License`.
- However, in the terms of use, it's mentioned that `Our Video-LLaMA is just a research preview intended for non-commercial use only`.

This is a bit confusing since the `BSD 3-Clause License` typically allows for commercial use. Could you please clarify the intended licensing terms for Video-LLAMA? and if we can use it for commercial purposes ? 

Thank you!

**Comment by lixin4ever** [comment]
Thanks for your attention.

First of all, the `BSD 3-Clause License` is inherited from MiniGPT-4 and BLIP-2.

Regarding your question, our Video-LLaMA with LLaMA-1 as the language decoder is not commercially usable. However,, the situation got better after the release of LLaMA-2, and our Video-LLaMA-2 (language decoder: LLaMA-2-Chat) is free to use once your affiliates satisfy the [official use policies](https://ai.meta.com/llama/license/#:~:text=You%20are%20granted%20a%20non,modifications%20to%20the%20Llama%20Materials) listed by Meta.

Note that you must NOT use our Video-LLaMA for any illegal, harmful, violent, racist, or sexual purposes.
