### ISSUE TITLE
llama_proj_model not passed to __init__

### ISSUE THREAD

**Issue by daahuang** [DAMO-NLP-SG/Video-LLaMA#92]
Hi,

Currently `llama_proj_model` is not passed to `__init__` in `from_config` of `VideoLLAMA`
As a result the checkpoint is never loaded [here](https://github.com/DAMO-NLP-SG/Video-LLaMA/blob/5a2718caa35bf07fe10c70208a7b88b2f79550c0/video_llama/models/video_llama.py#L156C9-L156C29). Even after this is fixed, `model` is also not defined [here](https://github.com/DAMO-NLP-SG/Video-LLaMA/blob/5a2718caa35bf07fe10c70208a7b88b2f79550c0/video_llama/models/video_llama.py#L159C19-L159C24).
From the keys (`llama_proj.weight`) of the [weights](https://drive.google.com/file/d/1a4zLvaiDBr-36pasffmgpvH5P7CKmpze/view) seems that the correct code is `self.load_state_dict(llama_proj_weight['model'], strict=False)`

**Comment by hangzhang-nlp** [comment]
Thanks a lot! It has been updated!
