### ISSUE TITLE
stage2 webvid数据集问题

### ISSUE THREAD

**Issue by Dylandtt** [DAMO-NLP-SG/Video-LLaMA#94]
![image](https://github.com/DAMO-NLP-SG/Video-LLaMA/assets/41997229/a0a37b87-3287-4d10-8596-5a8dffec52e9)
为什么我下载的webvid video中找不到这个video呢，是下载result_10M/2M_train/val中的哪个呢

**Comment by hangzhang-nlp** [comment]
stage2中的视频源自于webvid **10M**的训练数据。

**Comment by icemoon-creative** [comment]
这个video数据的命名是什么意思呢？

**Comment by shinever22** [comment]
Hi~We are researching a project, and the Webvid-2.5M dataset is very important to us. We found that the link is no longer working. Could you share this dataset with us?
shinever2022@gmail.com
