### ISSUE TITLE
Maybe some typo in video_llama_eval_only_vl.yaml

### ISSUE THREAD

**Issue by tiesanguaixia** [DAMO-NLP-SG/Video-LLaMA#96]
Thank you for your great work! 

1. First I have a question that if I run the demo with **only VL branch**, should I use the `video_llama_eval_only_vl.yaml` instead of the `video_llama_eval_withaudio.yaml` mentioned in _README_ ?
2. Secondly I found that the `equip_audio_branch` in `video_llama_eval_only_vl.yaml` is declared twice with different value. Is there some other modifications needed to correct the original `video_llama_eval_only_vl.yaml`?

Thank you in advance!

**Comment by lixin4ever** [comment]
1. Yes.
2. Please refer to the latest version of [video_llama_eval_only_vl.yaml](https://github.com/DAMO-NLP-SG/Video-LLaMA/blob/main/eval_configs/video_llama_eval_only_vl.yaml) where `equip_audio_branch` appears only once.
