### ISSUE TITLE
运行推理脚本python demo_audiovideo.py，如何指定多个gpu进行推理

### ISSUE THREAD

**Issue by 765144989** [DAMO-NLP-SG/Video-LLaMA#99]
python demo_audiovideo.py \
    --cfg-path eval_configs/video_llama_eval_withaudio.yaml \
    --model_type llama_v2 \ # or vicuna
    --gpu-id 0
    
   --gpu-id 0，可以指定多个gpu吗？

**Comment by hangzhang-nlp** [comment]
目前代码不支持多个GPU。
